// <auto-generated />
namespace QuizbeePlus.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddTblsAddedColHall_UC_Data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTblsAddedColHall_UC_Data));
        
        string IMigrationMetadata.Id
        {
            get { return "202105250834387_AddTblsAddedColHall_UC_Data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
